#= require "layout2/html5shiv-printshiv.js"
#= require "layout2/jquery.js"
#= require "layout2/jquery_ujs.js"
#= require "layout2/jquery-ui.js"
#= require "layout2/jquery.details.js"
#= require "layout2/jquery.textchange.js"
#= require "layout2/preorder.js"
#= require "layout2/application.js"